/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

// --- CONFIGURAÇÃO DO STRATEGIC DECISION ENGINE (SDE) ---

export const SDE_CONFIG = {
  // General Denominator/Norm for Weights
  WEIGHTS_DENOMINATOR: 15,

  // Constraints Constants
  CONSTRAINTS: {
    CLOSE_TO_EXAM_DAYS: 15,
    VETO_WEIGHT_THRESHOLD: 0.35,
    VETO_OPPORTUNITY_COST_THRESHOLD: 75,
    PREREQUISITE_MIN_HIT_RATE: 0.50,
  },

  // Priority Score Constants
  PRIORITY_SCORE: {
    MAX_PESO_EDITAL_SCORE: 15,
    PESO_EDITAL_MULT: 1.0,
    INCIDENCIA_MULT: 15,
    DEFICIENCIA_MULT: 20,
    ESQUECIMENTO_MULT: 15,
    RISCO_ESQUECIMENTO_MULT: 15,
    
    LEARNING_LEVERAGE_DEFAULT: 5,
    LEARNING_LEVERAGE_GOLDEN_MIN: 0.55,
    LEARNING_LEVERAGE_GOLDEN_MAX: 0.75,
    LEARNING_LEVERAGE_GOLDEN_SCORE: 15,
    
    LEARNING_LEVERAGE_SUB_GOLDEN_MIN: 0.40,
    LEARNING_LEVERAGE_SUB_GOLDEN_MAX: 0.55,
    LEARNING_LEVERAGE_SUB_GOLDEN_SCORE: 10,
    
    LEARNING_LEVERAGE_HIGH_MIN: 0.75,
    LEARNING_LEVERAGE_HIGH_MAX: 0.85,
    LEARNING_LEVERAGE_HIGH_SCORE: 8,
    
    LEARNING_LEVERAGE_MASTERED_MIN: 0.85,
    LEARNING_LEVERAGE_MASTERED_SCORE: 2,
    
    RISCO_ELIMINACAO_CRITICAL_SCORE: 30,
    RISCO_ELIMINACAO_WARN_SCORE: 20,
    RISCO_ELIMINACAO_WARN_MARGIN: 0.15,
    
    MAX_DEPENDENCIES_BONUS: 10,
    DEPENDENCY_MULTIPLIER: 3.3,
    
    CONFIDENCE_LOW_THRESHOLD_QC: 20,
    CONFIDENCE_LOW_VAL: 0.3,
    CONFIDENCE_MED_THRESHOLD_QC: 100,
    CONFIDENCE_MED_VAL: 0.7,
    CONFIDENCE_HIGH_VAL: 1.0,
    
    CONFIDENCE_DIAGNOSTIC_THRESHOLD: 0.5,
    CONFIDENCE_DIAGNOSTIC_BOOST: 25,
    CONFIDENCE_DIAGNOSTIC_PENALTY: 10,
    
    FLASHCARD_RISK_THRESHOLD: 5,
    FLASHCARD_HIT_RATE_THRESHOLD: 0.40,
    FLASHCARD_INAPPROPRIATE_PENALTY: 15,
    
    THEORY_MASTERED_HIT_RATE_THRESHOLD: 0.80,
    THEORY_MASTERED_PENALTY: 30,
  },

  // Recommendation Constants (XAI & Estimated Outputs)
  RECOMMENDATION: {
    RISCO_ELIMINACAO_THRESHOLD: 15,
    RISCO_ESQUECIMENTO_THRESHOLD: 10,
    CONFIDENCE_DIAGNOSTIC_THRESHOLD: 0.5,
    WEAK_HIT_RATE_THRESHOLD: 0.50,
    LEARNING_LEVERAGE_MAX: 15,
    
    CONFIDENCE_HIGH_THRESHOLD: 1.0,
    CONFIDENCE_MEDIUM_THRESHOLD: 0.7,
    
    MIN_RATING: 1,
    MAX_RATING: 10,
    
    GANHO_ESPERADO_DIVISOR: 2,
    RISCO_EVITADO_ELIMINACAO_DIVISOR: 3,
    RISCO_EVITADO_ESQUECIMENTO_DIVISOR: 2,
  }
};

export const DEFAULT_OPPORTUNITY_COST_POLICY = {
  minimumComparableActions: 2,
  durationToleranceRatio: 0.5,
};

export const DEFAULT_LEARNING_LEVERAGE_POLICY = {
  lowPerformanceUpperBound: 0.40,
  leverageZoneLowerBound: 0.55,
  leverageZoneUpperBound: 0.75,
  masteredLowerBound: 0.85,
};
